DROP TABLE Hierarchy
DROP TABLE Request
DROP TABLE Manager
DROP TABLE Fund

CREATE TABLE Request
(
  RequestId   INT IDENTITY
    CONSTRAINT PK_REQUEST PRIMARY KEY,
  requestType NVARCHAR(40) NOT NULL,
  dealName    NVARCHAR(50)
)
GO

CREATE TABLE Manager
(
  ManagerId   INT IDENTITY
    CONSTRAINT PK_MANAGER PRIMARY KEY,
  managerName NVARCHAR(40) NOT NULL,
  gfcId       NVARCHAR(50)
)
GO

CREATE TABLE Fund
(
  FundId   INT IDENTITY
    CONSTRAINT PK_FUND PRIMARY KEY,
  fundName NVARCHAR(40) NOT NULL,
  gfcId    NVARCHAR(50)
)
GO

CREATE TABLE Hierarchy
(
  Id        INT IDENTITY
    CONSTRAINT PK_HIERARCHY PRIMARY KEY,
  ManagerId INT          NOT NULL,
  FundId    INT          NOT NULL,
  RequestId INT          NOT NULL,
  type      NVARCHAR(20) NOT NULL
)
GO

ALTER TABLE Hierarchy
  ADD CONSTRAINT FK_Hierarchy_REFERENCE_MANAGER FOREIGN KEY (ManagerId)
REFERENCES Manager (ManagerId)
GO

ALTER TABLE Hierarchy
  ADD CONSTRAINT FK_Hierarchy_REFERENCE_FUND FOREIGN KEY (FundId)
REFERENCES Fund (FundId)
GO

ALTER TABLE Hierarchy
  ADD CONSTRAINT FK_Hierarchy_REFERENCE_REQUEST FOREIGN KEY (RequestId)
REFERENCES Request (RequestId)
GO